spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/otp"
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8088
  servlet:
    context-path: /otp

